<?php
namespace app\admin\controller;
use think\Controller;

class Index extends Common {
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db=new \app\admin\model\Information();
    }
    public function index(){
        return $this->fetch();
    }
    public function Information(){
        $article=$this->db->getArticle();
        $this->assign('article',$article);
        return $this->fetch();
    }
}